import type { FurnishItem } from "../furnishTypes";

/**
 * Business Officer Furnish — supporting UI abilities for Cases → Case doors.
 * Writing pass only; `status: "planted"` marks strips that exist in CT today.
 */
export const BUSINESS_FURNISH: FurnishItem[] = [
  {
    id: "biz-furnish-001",
    label: "Days-in-state",
    able: "Read days-in-state as a plain fact next to amount and locked contingency % on Status facts.",
    status: "planted",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Officers tracking filing progress had no elapsed-time fact on Status facts; delay felt opaque without a day count beside amount and contingency %.",
    implementation: "On Status facts, you can now read days-in-state as a plain fact next to amount and locked contingency %.",
  },
  {
    id: "biz-furnish-002",
    label: "Trust strip",
    able: "See no-upfront-fee and independent-verification copy on Notice — trust strip before Consent ticks.",
    status: "planted",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "Notice delivery matched documented impersonation patterns; officers needed an upfront trust bundle before Consent ticks, not fee absence alone.",
    implementation: "On Notice — trust strip, you can now read no upfront fee and an invite to verify the record independently before Consent ticks.",
  },
  {
    id: "biz-furnish-003",
    label: "Locked contingency %",
    able: "See contingency % shown as pre-set and locked at signing on Authorize door and Status facts.",
    status: "planted",
    surfaceIds: ["biz-ct-authorize","biz-ct-status"],
    implementationProblem: "Fee % could read as negotiable at authorize time; officers needed the signed percentage locked and repeated as a fact after filing.",
    implementation: "On Authorize door, you can now read contingency % as pre-set, locked at signing.\nOn Status facts, you can now read the same locked contingency % as a plain fact.",
  },
  {
    id: "biz-furnish-004",
    label: "State-pays-you fact",
    able: "Read on Paid fact and Invoice fact that the agency paid the business directly and Trove never held the funds.",
    status: "planted",
    surfaceIds: ["biz-ct-paid","biz-ct-invoice"],
    implementationProblem: "Post-disbursement records did not state remittance topology; officers could not confirm Trove never held claimant funds.",
    implementation: "On Paid fact, you can now read that the agency paid the business directly and Trove never held the funds.\nOn Invoice fact, you can now read the same state-pays-you fact beside the fee line.",
  },
  {
    id: "biz-furnish-005",
    label: "Kickback reason codes",
    able: "See the specific kickback reason label on Status facts instead of a generic denied label.",
    status: "planted",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Kicked_back Cases collapsed to a generic denied label; officers could not tell doc mismatch from entity or license issues.",
    implementation: "On Status facts, you can now read the specific kickback reason code label for a kicked_back Case instead of a generic denied label.",
  },
  {
    id: "biz-furnish-006",
    label: "Annual re-search enrolled chip",
    able: "See a quiet Annual re-search enrolled tag on Status facts after authorization.",
    status: "planted",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Annual monitoring enrollment was invisible after authorize; officers had no quiet confirmation on the Case status panel.",
    implementation: "On Status facts, you can now see a quiet Annual re-search enrolled tag under the main status panel after authorization.",
  },
  {
    id: "biz-furnish-007",
    label: "Filter Cases by admission state",
    able: "Filter Cases by admission state without opening each Case.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Cases list showed every Case in one flat index; officers opened each Case to see whether action was needed.",
    implementation: "On Cases, you can now filter rows by admission state without opening each Case.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-008",
    label: "Filter Cases by holding state",
    able: "Filter Cases by holding agency state from the Cases list.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Multi-state portfolios had no jurisdiction filter on Cases; officers scanned agency names row by row.",
    implementation: "On Cases, you can now filter rows by holding agency state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-009",
    label: "Filter Cases by amount range",
    able: "Filter Cases by reported amount range on the Cases list.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Priority triage by dollar size required opening each Case to read Notice — proof facts amount.",
    implementation: "On Cases, you can now filter rows by reported amount range.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-010",
    label: "Search Cases by caseRef",
    able: "Search Cases by caseRef or agency name from the Cases list.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Officers reconciling agency mail had no in-app search keyed to caseRef or agency name.",
    implementation: "On Cases, you can now search rows by caseRef or agency name.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-011",
    label: "Sort Cases columns",
    able: "Sort Cases by amount, last update, or days-in-state.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Cases row order was fixed; officers could not reorder by amount or elapsed filing time.",
    implementation: "On Cases, you can now sort rows by amount, last update, or days-in-state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-012",
    label: "Export Cases to CSV",
    able: "Export the Cases list to CSV for spreadsheet review.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Finance and ops reviews needed a portable Cases extract without retyping row facts.",
    implementation: "On Cases, you can now export the visible row set to CSV.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-013",
    label: "Export Cases summary PDF",
    able: "Export a Cases summary PDF for internal reporting.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Board or treasury updates required a printable portfolio snapshot not available from Cases.",
    implementation: "On Cases, you can now export a summary PDF of the visible row set.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-014",
    label: "Multi-case glance",
    able: "Open a Multi-case glance panel with counts by admission state and holding state.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Officers lacked a one-screen portfolio rollup before drilling into individual Case doors.",
    implementation: "On Cases, you can now open Multi-case glance with counts by admission state and holding state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-015",
    label: "Compare Cases",
    able: "Compare two Cases side-by-side on amount, state, and status facts.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases","biz-ct-case"],
    implementationProblem: "Similar holdings in different states required opening two Case modals and mentally diffing facts.",
    implementation: "On Cases, you can now select two rows and open Compare Cases with amount, holding state, and Status facts side-by-side.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-016",
    label: "Print Cases summary",
    able: "Print a Cases summary sheet from the Cases list.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Physical filing cabinets and sign-off packets had no print path from the Cases module.",
    implementation: "On Cases, you can now print a summary sheet of the visible row set.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-017",
    label: "Case milestone calendar",
    able: "View Case milestones on a calendar by authorize date, filing date, and paid date.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Treasury planning needed milestone dates in calendar form, not only per-Case Status facts.",
    implementation: "On Cases, you can now open Case milestone calendar keyed to authorize, filing, and Paid fact dates.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-018",
    label: "Status-change email alert",
    able: "Opt in to email when a Case admission state changes.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Officers checked Cases manually for kicks, pays, and filings instead of receiving state-change signal.",
    implementation: "On Status facts, you can now opt in to email when the Case admission state changes.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-019",
    label: "Weekly Cases digest",
    able: "Opt in to a weekly Cases digest email summarizing open and action-needed rows.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Busy officers missed stale filing rows without a periodic portfolio digest.",
    implementation: "On Cases, you can now opt in to a weekly digest email summarizing open and action-needed rows.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-020",
    label: "Share Case with counsel",
    able: "Share a read-only Case link with outside counsel without granting officer authority.",
    status: "deferred",
    surfaceIds: ["biz-ct-case","biz-ct-status"],
    implementationProblem: "Legal review required exporting screenshots because counsel could not view Case facts read-only.",
    implementation: "On Case, you can now share a read-only link scoped to Notice — proof facts, Status facts, and Upload packet status.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-021",
    label: "Share Case with accountant",
    able: "Share a read-only Case link with the company accountant for tax prep.",
    status: "deferred",
    surfaceIds: ["biz-ct-case","biz-ct-paid","biz-ct-invoice"],
    implementationProblem: "Accountants re-requested Paid fact and Invoice fact details because no read-only share existed.",
    implementation: "On Case, you can now share a read-only link scoped to Paid fact, Invoice fact, and Authorize door fee terms.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-022",
    label: "Tax Treatment door",
    able: "Open a Tax Treatment door from Consent ticks with gross-vs-net framing without Trove tax advice.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Consent ticks carried no tax-timing context; officers signed without a neutral gross-vs-net copy door.",
    implementation: "On Consent ticks, you can now open Tax Treatment door with gross-vs-net framing and accountant-determination disclaimer.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-023",
    label: "Tax timing disclosure line",
    able: "Read a tax-timing disclosure line on Consent ticks before authorization.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Recovery in one period and Trove fee invoice in another was unstated at consent time.",
    implementation: "On Consent ticks, you can now read a tax-timing disclosure line stating recovery and fee may fall in different tax periods.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-024",
    label: "1099 guidance door",
    able: "Open a 1099 guidance door from Invoice fact describing fee reporting expectations.",
    status: "deferred",
    surfaceIds: ["biz-ct-invoice"],
    implementationProblem: "AP teams lacked in-product copy on how to classify Trove's contingency fee for 1099 reporting.",
    implementation: "On Invoice fact, you can now open 1099 guidance door with vendor-classification copy for AP records.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-025",
    label: "Per-state expectation window",
    able: "Read the holding state's published processing expectation on Status facts beside days-in-state.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Days-in-state alone invited Trove-SLA fiction; officers needed the state's own expectation window cited.",
    implementation: "On Status facts, you can now read the holding state's published processing expectation beside days-in-state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-026",
    label: "Export status timeline",
    able: "Export Status facts timeline for one Case as CSV.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Audit requests for filing history required manual copy from Status facts.",
    implementation: "On Status facts, you can now export the Case status timeline as CSV.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-027",
    label: "Print Status facts",
    able: "Print Status facts for one Case for internal records.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Internal claim files had no print layout for Status facts and kickback reason codes.",
    implementation: "On Status facts, you can now print a one-Case status sheet including kickback reason when present.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-028",
    label: "Kickback action checklist",
    able: "Open a kickback action checklist keyed to the specific kickback reason code.",
    status: "deferred",
    surfaceIds: ["biz-ct-status","biz-ct-upload"],
    implementationProblem: "Specific kickback labels did not translate into doc tasks officers could follow on Upload packet.",
    implementation: "On Status facts, when kicked_back you can now open Kickback action checklist keyed to the kickback reason code with Upload packet tasks.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-029",
    label: "Resubmit readiness tag",
    able: "See a Resubmit readiness tag when required Upload packet items are complete.",
    status: "deferred",
    surfaceIds: ["biz-ct-status","biz-ct-upload"],
    implementationProblem: "Officers could not tell when a kicked_back Case was ready for agency resubmit without re-reading Upload packet.",
    implementation: "On Status facts, you can now see Resubmit readiness tag when Upload packet required items are complete.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-030",
    label: "Verify-yourself link",
    able: "Open a verify-yourself link from Notice — trust strip to the agency's own search site.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust","biz-ct-notice"],
    implementationProblem: "Notice — proof facts cited agency and caseRef but offered no independent lookup path.",
    implementation: "On Notice — trust strip, you can now open verify-yourself link to the holding agency's official search or claim-status site.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-031",
    label: "Non-affiliation line",
    able: "Read a mandatory non-affiliation line on Notice — trust strip.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "Finder outreach could read as state employment; Notice — trust strip lacked an affirmative non-affiliation line.",
    implementation: "On Notice — trust strip, you can now read mandatory non-affiliation line stating Trove is not the holding agency.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-032",
    label: "Official agency domain",
    able: "Read official agency domain and contact channel on Notice — trust strip.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "Officers could not compare Trove delivery channel against the agency's published domain and contact.",
    implementation: "On Notice — trust strip, you can now read official agency domain and contact channel for the holding state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-033",
    label: "State fraud bulletin link",
    able: "Open the holding state's consumer fraud page from Notice — trust strip when configured.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "Generic trust copy ignored state-published anti-scam pages officers already trust.",
    implementation: "On Notice — trust strip, you can now open link to the holding state's consumer fraud page when one is configured.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-034",
    label: "Finder registry lookup",
    able: "Open finder license lookup from Notice — trust strip when Trove holds standing.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "States with finder registries expect officers to confirm locator license; Notice had no lookup link.",
    implementation: "On Notice — trust strip, when Trove holds standing you can now open finder registry lookup for the holding state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-035",
    label: "Scam-category block",
    able: "Read a Scam-category block on Notice — trust strip naming red flags Trove does not use.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "Documented impersonation patterns were unnamed; officers could not map Trove structure against published red flags.",
    implementation: "On Notice — trust strip, you can now read Scam-category block listing documented red flags with explicit negation for each.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-036",
    label: "Amount-as-reported date",
    able: "Read amount labeled as reported by agency as of date on Notice — proof facts.",
    status: "deferred",
    surfaceIds: ["biz-ct-notice"],
    implementationProblem: "Notice amount lacked as-of dating; officers treated reported balance as current without agency timestamp.",
    implementation: "On Notice — proof facts, you can now read amount labeled as reported by agency as of date.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-037",
    label: "Print Notice packet",
    able: "Print Notice — proof facts and Notice — trust strip together for board review.",
    status: "deferred",
    surfaceIds: ["biz-ct-notice","biz-ct-trust"],
    implementationProblem: "Board packets required manual assembly of notice proof and trust copy.",
    implementation: "On Case, you can now print Notice packet combining Notice — proof facts and Notice — trust strip.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-038",
    label: "Export Notice PDF",
    able: "Export Notice — proof facts as PDF for internal records.",
    status: "deferred",
    surfaceIds: ["biz-ct-notice"],
    implementationProblem: "Records teams saved screenshots because Notice had no export path.",
    implementation: "On Notice — proof facts, you can now export a PDF of the proof block.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-039",
    label: "Consent snapshot for audit",
    able: "Download a Consent ticks snapshot PDF timestamped at authorization.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Post-hoc disputes lacked immutable copy of tick text the officer accepted.",
    implementation: "On Consent ticks, after authorization you can now download Consent snapshot PDF timestamped at authorize.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-040",
    label: "Before/after fee dollars",
    able: "Read before/after fee dollar example on Authorize door beside locked contingency %.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Some states require pre/post dollar estimates; Authorize door showed percentage only.",
    implementation: "On Authorize door, you can now read before/after fee dollar example computed from Notice amount and locked contingency %.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-041",
    label: "Fee basis footnote",
    able: "Read fee basis footnote on Authorize door stating contingency applies to recovered amount before fee.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Percentage disclosure could imply net-only tax framing without gross-recovery basis stated.",
    implementation: "On Authorize door, you can now read fee basis footnote that contingency applies to recovered amount before fee.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-042",
    label: "Estimated fee range",
    able: "Read estimated fee range on Authorize door when Notice amount may revise.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Upward amount revisions before pay were unstated at authorize time.",
    implementation: "On Authorize door, you can now read estimated fee range when Notice amount carries revision risk.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-043",
    label: "Print Authorize summary",
    able: "Print Authorize door summary before e-sign for internal sign-off.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Dual-signer companies needed a paper summary before the officer e-signed.",
    implementation: "On Authorize door, you can now print Authorize summary before completing e-sign.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-044",
    label: "Download signed authorization",
    able: "Download signed authorization PDF after Authorize door completes.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Corporate records required a retained copy of the executed authorization.",
    implementation: "On Authorize door, after e-sign you can now download signed authorization PDF.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-045",
    label: "Upload checklist progress",
    able: "See Upload packet checklist with completion percentage.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Required docs were listed without aggregate completion signal.",
    implementation: "On Upload packet, you can now see checklist progress with completion percentage.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-046",
    label: "Upload document preview",
    able: "Preview uploaded documents inline on Upload packet without downloading.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Officers re-downloaded each upload to confirm the correct file was attached.",
    implementation: "On Upload packet, you can now preview each uploaded document inline.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-047",
    label: "Upload missing-doc highlight",
    able: "See missing required documents highlighted on Upload packet.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Incomplete packets were submitted because missing items were not visually distinct.",
    implementation: "On Upload packet, you can now see missing required documents highlighted until satisfied.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-048",
    label: "Securities template download",
    able: "Download securities claim template from Upload packet when asset type requires it.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Securities holdings needed state-specific templates not bundled in Upload packet.",
    implementation: "On Upload packet, when asset type is securities you can now download securities claim template.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-049",
    label: "Insurance template download",
    able: "Download insurance claim template from Upload packet when asset type requires it.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Insurance proceeds claims lacked an in-product template path on Upload packet.",
    implementation: "On Upload packet, when asset type is insurance you can now download insurance claim template.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-050",
    label: "Affidavit-of-loss path",
    able: "Open affidavit-of-loss path on Upload packet when original negotiable instrument is unavailable.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Missing original instruments blocked upload with no corporate-resolution alternative.",
    implementation: "On Upload packet, you can now open affidavit-of-loss path with corporate-resolution alternative when original is unavailable.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-051",
    label: "Revival certificate template",
    able: "Download revival certificate template from Upload packet for dissolved entities.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Dissolved-entity revivals required external research for certificate format.",
    implementation: "On Upload packet, when entity status requires revival you can now download revival certificate template.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-052",
    label: "State affirmation template",
    able: "Download state affirmation template from Upload packet when jurisdiction requires it.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "State-specific affirmations were not surfaced beside Upload packet requirements.",
    implementation: "On Upload packet, you can now download state affirmation template when the holding state requires it.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-053",
    label: "Print Upload manifest",
    able: "Print Upload packet manifest listing attached documents.",
    status: "deferred",
    surfaceIds: ["biz-ct-upload"],
    implementationProblem: "Mail-original filings needed a manifest officers could include with physical packets.",
    implementation: "On Upload packet, you can now print Upload manifest listing attached documents and caseRef.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-054",
    label: "Bank confirmation copy",
    able: "Copy bank confirmation details from Paid fact for treasury reconciliation.",
    status: "deferred",
    surfaceIds: ["biz-ct-paid"],
    implementationProblem: "Treasury matched deposits manually from Paid fact without a copy action.",
    implementation: "On Paid fact, you can now copy bank confirmation details for treasury reconciliation.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-055",
    label: "Export Paid fact",
    able: "Export Paid fact row for AP and treasury systems.",
    status: "deferred",
    surfaceIds: ["biz-ct-paid"],
    implementationProblem: "ERP import required retyping Paid fact dates and amounts.",
    implementation: "On Paid fact, you can now export paid amount, date, and caseRef as CSV.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-056",
    label: "Export Invoice fact",
    able: "Export Invoice fact row for AP processing.",
    status: "deferred",
    surfaceIds: ["biz-ct-invoice"],
    implementationProblem: "Invoice fact details were not available in a portable export for AP.",
    implementation: "On Invoice fact, you can now export fee amount, date, and caseRef as CSV.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-057",
    label: "Invoice dispute door",
    able: "Open Invoice dispute door from Invoice fact with reason picker.",
    status: "deferred",
    surfaceIds: ["biz-ct-invoice"],
    implementationProblem: "Fee disputes had no structured in-product path tied to Invoice fact.",
    implementation: "On Invoice fact, you can now open Invoice dispute door with reason picker and caseRef recap.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-058",
    label: "Print Invoice fact",
    able: "Print Invoice fact for accounts payable records.",
    status: "deferred",
    surfaceIds: ["biz-ct-invoice"],
    implementationProblem: "AP filing required screenshots because Invoice fact had no print layout.",
    implementation: "On Invoice fact, you can now print a fee invoice sheet for AP records.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-059",
    label: "Invoice-to-Case trace lines",
    able: "Read Invoice fact lines tying fee to Case caseRef, Authorize date, and Paid fact date.",
    status: "deferred",
    surfaceIds: ["biz-ct-invoice"],
    implementationProblem: "Contingency fee could not be traced to specific authorization and disbursement in one view.",
    implementation: "On Invoice fact, you can now read lines tying invoice to Case caseRef, Authorize date, and Paid fact date.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-060",
    label: "Decline reason picker",
    able: "Pick a decline reason code on Decline door before confirming.",
    status: "deferred",
    surfaceIds: ["biz-ct-decline"],
    implementationProblem: "Decline door lacked structured reason capture for internal records.",
    implementation: "On Decline door, you can now pick decline reason code before confirming decline.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-061",
    label: "Decline confirmation receipt",
    able: "Download decline confirmation receipt after Decline door completes.",
    status: "deferred",
    surfaceIds: ["biz-ct-decline"],
    implementationProblem: "Officers had no retained proof a Case was declined before authorization.",
    implementation: "On Decline door, after confirm you can now download decline confirmation receipt with timestamp.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-062",
    label: "Officer memo on Case",
    able: "Add a private officer memo on Case visible only to your company login.",
    status: "deferred",
    surfaceIds: ["biz-ct-case"],
    implementationProblem: "Internal context lived in email threads outside the Case record.",
    implementation: "On Case, you can now add Officer memo notes visible only to your company login.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-063",
    label: "Case activity timeline",
    able: "View Case activity timeline summarizing door opens and state changes.",
    status: "deferred",
    surfaceIds: ["biz-ct-case"],
    implementationProblem: "Officers reconstructed history from scattered Status facts without a unified timeline.",
    implementation: "On Case, you can now view Case activity timeline summarizing door opens and admission state changes.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-064",
    label: "Audit log glance",
    able: "Open Audit log glance on Case showing Trove actions under POA.",
    status: "deferred",
    surfaceIds: ["biz-ct-case"],
    implementationProblem: "Legitimacy disputes lacked an officer-visible Trove action trail on the Case.",
    implementation: "On Case, you can now open Audit log glance listing Trove actions under POA for that Case.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-065",
    label: "Bookmark Case",
    able: "Bookmark a Case on Cases for quick return.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "High-priority Cases were re-found by search each session.",
    implementation: "On Cases, you can now bookmark a row for quick return from a Bookmarked filter.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-066",
    label: "Hide declined Cases",
    able: "Toggle Hide declined Cases on the Cases list.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Declined rows cluttered the active portfolio view.",
    implementation: "On Cases, you can now toggle Hide declined Cases on the list.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-067",
    label: "Action-needed filter",
    able: "Filter Cases to action-needed rows only.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Officers scanned the full list to find kicked_back and consented rows needing work.",
    implementation: "On Cases, you can now filter to action-needed rows only.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-068",
    label: "Cases column picker",
    able: "Choose which columns appear on the Cases list.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Fixed columns hid facts some officers wanted visible at glance.",
    implementation: "On Cases, you can now open Cases column picker to show or hide amount, state, days-in-state, and status.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-069",
    label: "Cases amount total",
    able: "See reported amount total for the visible Cases filter set.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Portfolio dollar exposure required exporting to spreadsheet for a sum.",
    implementation: "On Cases, you can now read reported amount total for the visible filter set in the list footer.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-070",
    label: "Recovery pipeline chart",
    able: "View recovery pipeline chart grouped by admission state on Cases.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "State distribution was numeric-only in Multi-case glance without visual weight.",
    implementation: "On Cases, you can now open recovery pipeline chart grouped by admission state.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-071",
    label: "Duplicate caseRef warning",
    able: "See duplicate caseRef warning when two Cases share the same agency reference.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Duplicate agency references could pass unnoticed in a flat Cases list.",
    implementation: "On Cases, you can now see duplicate caseRef warning when two rows share the same agency reference.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-072",
    label: "Agency contact card",
    able: "Open holding agency contact card from Case with phone and web from jurisdiction registry.",
    status: "deferred",
    surfaceIds: ["biz-ct-case","biz-ct-notice"],
    implementationProblem: "Officers left Case to find agency contact details during kickback follow-up.",
    implementation: "On Case, you can now open Agency contact card with phone and web sourced from jurisdiction registry.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-073",
    label: "Filing method badge",
    able: "See Filing method badge on Status facts for digital, mail-original, or notarized-original.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Physical-mail jurisdictions looked identical to digital filing on Status facts.",
    implementation: "On Status facts, you can now see Filing method badge for digital, mail-original, or notarized-original.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-074",
    label: "Packet dispatched substatus",
    able: "Read packet_dispatched substatus on Status facts when filing method is mail-original.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Mail lag was conflated with under review; days-in-state started too early.",
    implementation: "On Status facts, when Filing method is mail-original you can now read packet_dispatched substatus before under review.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-075",
    label: "Revised amount fact",
    able: "Read revised amount fact on Status facts when agency updates reported balance.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Amount changes after Notice were invisible on Status facts.",
    implementation: "On Status facts, you can now read revised amount fact when agency updates reported balance.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-076",
    label: "Legal research flag",
    able: "See legal research flag on Status facts when holding type triggers review.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Complex asset types gave no quiet signal that legal review was expected.",
    implementation: "On Status facts, you can now see legal research flag when holding type triggers review.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-077",
    label: "Re-affirm door",
    able: "Open Re-affirm door from Status facts when agency requests re-confirmation.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Agency re-confirmation requests had no officer door on Status facts.",
    implementation: "On Status facts, you can now open Re-affirm door when agency requests re-confirmation.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-078",
    label: "Withdraw door",
    able: "Open Withdraw door from Status facts to cancel an in-flight Case.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Officers could not initiate withdrawal from an active filing without agency email.",
    implementation: "On Status facts, you can now open Withdraw door to request cancellation of an in-flight Case.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-079",
    label: "Wage classification note",
    able: "Read wage/legal classification note on Status facts for payroll-type holdings.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Payroll escheatments carried classification nuance not surfaced on Status facts.",
    implementation: "On Status facts, for payroll-type holdings you can now read wage/legal classification note.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-080",
    label: "Denied standing explanation",
    able: "Read denied standing explanation on Status facts when agency rejects authority.",
    status: "deferred",
    surfaceIds: ["biz-ct-status"],
    implementationProblem: "Authority denials collapsed to opaque status without officer-readable explanation.",
    implementation: "On Status facts, you can now read denied standing explanation when agency rejects authority.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-081",
    label: "Notification preferences",
    able: "Set notification preferences for status email and digest on Settings.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Email alert opt-ins lived per Case without a company-wide default.",
    implementation: "On Settings, you can now set notification preferences for status email and weekly Cases digest.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-082",
    label: "Default export format",
    able: "Set default export format for Cases and status exports on Settings.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Repeat exports required choosing CSV or PDF each time.",
    implementation: "On Settings, you can now set default export format for Cases and Status facts exports.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-083",
    label: "Officer display name",
    able: "Set officer display name on Settings used on Authorize door and exports.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Exports and signed PDFs used login email instead of officer name on file.",
    implementation: "On Settings, you can now set officer display name surfaced on Authorize door and exports.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-084",
    label: "Copy caseRef",
    able: "Copy caseRef to clipboard from Cases row actions.",
    status: "deferred",
    surfaceIds: ["biz-ct-cases"],
    implementationProblem: "Officers retyped agency references when calling the holding agency.",
    implementation: "On Cases, you can now copy caseRef to clipboard from row actions.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-085",
    label: "Copy agency case ID",
    able: "Copy agency case ID from Notice — proof facts.",
    status: "deferred",
    surfaceIds: ["biz-ct-notice"],
    implementationProblem: "Agency phone support required manual transcription of proof facts identifiers.",
    implementation: "On Notice — proof facts, you can now copy agency case ID to clipboard.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-086",
    label: "Deep link to Case door",
    able: "Copy deep link to a specific Case door for internal handoff.",
    status: "deferred",
    surfaceIds: ["biz-ct-case"],
    implementationProblem: "Colleagues reopened Cases from email descriptions instead of the exact door state.",
    implementation: "On Case, you can now copy deep link opening that Case door directly.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-087",
    label: "Claim form packet door",
    able: "Open Claim form packet from Authorize door when Filing method is not digital.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Non-digital states required wet-ink forms not reachable from Authorize door.",
    implementation: "On Authorize door, when Filing method is not digital you can now open Claim form packet.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-088",
    label: "Notary instructions download",
    able: "Download notary instructions from Claim form packet when Filing method is notarized-original.",
    status: "deferred",
    surfaceIds: ["biz-ct-authorize"],
    implementationProblem: "Notarized-original filings lacked bundled notary guidance beside the claim form.",
    implementation: "On Claim form packet, when Filing method is notarized-original you can now download notary instructions.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-089",
    label: "Post-authorize steps checklist",
    able: "Read post-authorize steps checklist on Case after Authorize door completes.",
    status: "deferred",
    surfaceIds: ["biz-ct-case","biz-ct-upload"],
    implementationProblem: "Officers did not know Upload packet and mail steps order after signing.",
    implementation: "On Case, after Authorize door you can now read post-authorize steps checklist through Upload packet.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-090",
    label: "Entity identity confirmation",
    able: "Confirm entity identity on Consent ticks before dollar detail unlocks.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Wrong-entity consent was possible without an explicit identity match step.",
    implementation: "On Consent ticks, you can now confirm entity identity before dollar detail unlocks.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-091",
    label: "Signer title capture",
    able: "Enter signer title on Consent ticks for corporate authority records.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Authorization records lacked officer title beside name on Consent ticks.",
    implementation: "On Consent ticks, you can now enter signer title stored with authorization records.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-092",
    label: "Knowledge attestation tick",
    able: "Complete knowledge attestation tick on Consent ticks where jurisdiction requires it.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Some states require knowledge attestation not present in generic Consent ticks.",
    implementation: "On Consent ticks, you can now complete knowledge attestation tick when jurisdiction requires it.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-093",
    label: "Indemnification copy door",
    able: "Open Indemnification copy door from Consent ticks for full indemnity text.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Indemnification terms were truncated on Consent ticks without a full-text door.",
    implementation: "On Consent ticks, you can now open Indemnification copy door with full indemnity text.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-094",
    label: "Fee obligor disclosure",
    able: "Read fee obligor disclosure on Consent ticks naming who owes the contingency fee.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Fee obligor was implicit in Authorize door only; Consent lacked obligor naming.",
    implementation: "On Consent ticks, you can now read fee obligor disclosure naming who owes the contingency fee.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-095",
    label: "Default vs offered fee",
    able: "Compare default vs offered fee on Consent ticks when states publish fee caps.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent"],
    implementationProblem: "Officers could not see statutory default fee beside Trove offered percentage at consent.",
    implementation: "On Consent ticks, you can now compare default vs offered fee when holding state publishes fee caps.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-096",
    label: "Reciprocal reporting note",
    able: "Read reciprocal reporting note on Notice — proof facts for multi-state holders.",
    status: "deferred",
    surfaceIds: ["biz-ct-notice"],
    implementationProblem: "Multi-state holder reporting obligations were unstated at notice time.",
    implementation: "On Notice — proof facts, you can now read reciprocal reporting note for multi-state holders when applicable.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-097",
    label: "Dual role disclosure",
    able: "Read dual role disclosure on Notice — proof facts when Trove acts as finder and processor.",
    status: "deferred",
    surfaceIds: ["biz-ct-notice"],
    implementationProblem: "Combined finder and processing roles were not disclosed on Notice — proof facts.",
    implementation: "On Notice — proof facts, you can now read dual role disclosure when Trove acts as finder and processor.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-098",
    label: "No-escrow reaffirmation",
    able: "Read no-escrow reaffirmation on Paid fact beside state-pays-you fact.",
    status: "deferred",
    surfaceIds: ["biz-ct-paid"],
    implementationProblem: "Post-pay reassurance that Trove never held funds was only on initial Notice — trust strip.",
    implementation: "On Paid fact, you can now read no-escrow reaffirmation beside state-pays-you fact.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-099",
    label: "Trust bundle condensed view",
    able: "Toggle condensed trust bundle on Notice — trust strip for repeat Cases.",
    status: "deferred",
    surfaceIds: ["biz-ct-trust"],
    implementationProblem: "Repeat officers saw full trust prose on every Case without a condensed path.",
    implementation: "On Notice — trust strip, you can now toggle condensed trust bundle for repeat Cases.",
    implementationPlant: "not_done",
  },
  {
    id: "biz-furnish-100",
    label: "CaseRef recap on Consent",
    able: "Read caseRef recap on Consent ticks matching Notice — proof facts.",
    status: "deferred",
    surfaceIds: ["biz-ct-consent","biz-ct-notice"],
    implementationProblem: "Consent screen did not repeat caseRef; officers verified against prior Notice manually.",
    implementation: "On Consent ticks, you can now read caseRef recap matching Notice — proof facts.",
    implementationPlant: "not_done",
  },
];
