/**
 * CTO Wiring — machine twin of `docs/wiring/WIRING.md` for Trim protest
 * obligations. Wiring is specification-only: CAD/ARB/ACH-style dependencies
 * are named design obligations, not claims of live external integrations.
 */
export type WiringStatus = "implemented" | "partial" | "deferred" | "wiring";

export type WiringFacet = {
  id: string;
  label: string;
  status: WiringStatus;
  flowIds: string[];
  surfaceIds: string[];
  notes?: string;
};

export const WIRING_FUNCTION: WiringFacet[] = [
  {
    id: "wf-01-detection",
    label: "Detection jobs",
    status: "wiring",
    flowIds: ["activate-notice"],
    surfaceIds: [],
    notes: "Always-on county roll/CAMA/comp scanning is designed, not backend-connected. It must produce parcel confidence and trust-kit facts before outreach.",
  },
  {
    id: "wf-02-valuation-substantiation-copy-gate",
    label: "Valuation substantiation and copy gate",
    status: "wiring",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-owner-notice", "trim-ct-op-exceptions"],
    notes: "Blocks detected -> notified unless valuation support, reviewer approval, approved claim text, and channel constraints are present.",
  },
  {
    id: "wf-03-jurisdiction-registry-pre-notice-gate",
    label: "Jurisdiction registry and pre-notice gate",
    status: "partial",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-op-jurisdiction"],
    notes: "CT shows county standing as an operating flag; the full representative type, PTC capacity, solicitation, portal, and calendar registry is still wiring.",
  },
  {
    id: "wf-04-trust-kit-persistence",
    label: "Trust kit persistence",
    status: "partial",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-owner-trust", "trim-ct-owner-notice"],
    notes: "Owner notice surfaces trust facts; first-class persistence, CAD URL QA, data snapshot IDs, and stale-field suppression remain designed obligations.",
  },
  {
    id: "wf-05-alg-activation-delivery",
    label: "ALG activation delivery",
    status: "implemented",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-owner-notice", "trim-ct-owner-trust"],
    notes: "CT demonstrates the UI consequence: a served Owner notice with parcel proof and trust strip. Detection, channel delivery, and gates remain design-only automation.",
  },
  {
    id: "wf-06-consent-appointment-agent-capture",
    label: "Consent and Appointment of Agent capture",
    status: "implemented",
    flowIds: ["consent-authorize"],
    surfaceIds: ["trim-ct-owner-consent", "trim-ct-owner-authorize"],
    notes: "CT demonstrates consent ticks, authorization, and locked terms. Provider callbacks, signer validation, and jurisdiction computation remain specification wiring.",
  },
  {
    id: "wf-07-evidence-preparation",
    label: "Evidence preparation",
    status: "partial",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-upload", "trim-ct-owner-status"],
    notes: "Upload and evidence status surfaces exist; automated comps/equity/income packet building and ARB-retainable packaging are not live integrations.",
  },
  {
    id: "wf-08-informal-review",
    label: "Informal review",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-status", "trim-ct-op-exceptions"],
    notes: "Informal submission and offer capture are designed county-specific state facts, not connected CAD portal automation.",
  },
  {
    id: "wf-09-worker-dispatch-state-machine",
    label: "Worker dispatch state machine",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: [
      "trim-ct-op-worker-dispatch",
      "trim-ct-worker-queue",
      "trim-ct-worker-packet",
      "trim-ct-worker-assignment",
      "trim-ct-worker-hearing",
      "trim-ct-worker-outcome",
    ],
    notes: "Worker queue, Form 50-162 authority proof, appearance mode, checklist, no-show codes, and outcome reporting are named design obligations.",
  },
  {
    id: "wf-10-outcome-reduction-recording",
    label: "Outcome and reduction recording",
    status: "wiring",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-worker-outcome", "trim-ct-owner-reduction", "trim-ct-op-collections"],
    notes: "Reduced/denied/continued outcome facts and measured savings must be persisted from the Worker report; calculator is a spec obligation.",
  },
  {
    id: "wf-11-invoice-generation-collections",
    label: "Invoice generation and collections",
    status: "wiring",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-invoice", "trim-ct-op-collections"],
    notes: "Invoice-after-reduction, ACH/card authorization reference, dunning, and dispute intake are design wiring. Trim never holds escrow.",
  },
  {
    id: "wf-12-recurrence-state-machine",
    label: "Recurrence state machine",
    status: "wiring",
    flowIds: [],
    surfaceIds: ["trim-ct-owner-status"],
    notes: "Recurring annual re-detection and POA reuse/renewal are designed state-machine obligations; no recurring flow map exists yet.",
  },
  {
    id: "wf-13-escrow-lender-reserve-branch",
    label: "Escrow / lender reserve branch",
    status: "deferred",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-op-collections"],
    notes: "Servicer evidence, reserve release tracking, and felt-win timing are deferred. Reduced must not imply cash_received.",
  },
  {
    id: "wf-14-post-arb-escalation-lanes",
    label: "Post-ARB escalation lanes",
    status: "deferred",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-op-exceptions"],
    notes: "RBA, SOAH, district court, settlement, and counsel lanes require separate authority, deposits, deadlines, and remedy election.",
  },
  {
    id: "wf-15-audit-trail",
    label: "Audit trail",
    status: "implemented",
    flowIds: [],
    surfaceIds: ["trim-ct-op-audit"],
    notes: "CT demonstrates the audit surface. Append-only storage, event immutability, and export enforcement remain backend design obligations.",
  },
  {
    id: "wf-16-county-data-ingest-pipeline",
    label: "County data ingest pipeline",
    status: "partial",
    flowIds: [],
    surfaceIds: ["trim-ct-op-county-data"],
    notes: "County data health exists in CT; roll adapters, CAMA schema versions, freshness monitors, PIA fallback, and cost model remain partial.",
  },
  {
    id: "wf-17-texas-ptc-capacity-registry",
    label: "Texas PTC capacity registry",
    status: "partial",
    flowIds: [],
    surfaceIds: ["trim-ct-op-jurisdiction"],
    notes: "CT shows jurisdiction capacity; named-human PTC sponsorship, max-10 supervision, renewal, CE, and reassignment controls remain partial.",
  },
  {
    id: "wf-18-owner-tax-accounting-artifacts",
    label: "Owner tax / accounting artifacts",
    status: "deferred",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-invoice", "trim-ct-owner-reduction"],
    notes: "Corrected bill, board order, invoice date, W-9/1099 support, and sales-taxability holds are deferred accounting artifacts.",
  },
  {
    id: "wf-19-apis",
    label: "APIs",
    status: "wiring",
    flowIds: [],
    surfaceIds: [],
    notes: "Internal protest-case CRUD, state transitions, gate checks, evidence triggers, dispatch, outcome, invoice, collections, and audit APIs are specified only.",
  },
  {
    id: "wf-20-observability",
    label: "Observability",
    status: "wiring",
    flowIds: [],
    surfaceIds: [],
    notes: "Detection funnel, consent-to-collection, hearing outcomes, dispatch latency, evidence latency, collections, and county freshness metrics are specified only.",
  },
];

export const WIRING_CANTS: WiringFacet[] = [
  {
    id: "wc-multi-entity-owner",
    label: "Multi-entity Owner login aggregation",
    status: "deferred",
    flowIds: [],
    surfaceIds: ["trim-ct-owner-portfolio"],
    notes: "Requires entity-to-login join and cross-entity read scoping.",
  },
  {
    id: "wc-read-only-share",
    label: "Read-only case share links (counsel / accountant scoped)",
    status: "deferred",
    flowIds: [],
    surfaceIds: ["trim-ct-owner-case"],
    notes: "Scoped token with surface-level read ACL.",
  },
  {
    id: "wc-notification-prefs",
    label: "State-change email and digest subscription system",
    status: "deferred",
    flowIds: [],
    surfaceIds: ["trim-ct-owner-status"],
    notes: "Requires notification preference store per Owner login.",
  },
  {
    id: "wc-informal-offer-field",
    label: "Informal offer amount as first-class field on protest case",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-status", "trim-ct-op-exceptions"],
    notes: "Named field needed in WF-08; not yet in schema.",
  },
  {
    id: "wc-hearing-logistics-visible",
    label: "Hearing date / board / venue on Owner status",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-status", "trim-ct-worker-hearing"],
    notes: "Requires WF-09 to persist hearing logistics.",
  },
  {
    id: "wc-poa-download",
    label: "Signed Appointment of Agent PDF download",
    status: "deferred",
    flowIds: ["consent-authorize"],
    surfaceIds: ["trim-ct-owner-authorize"],
    notes: "E-signature provider must support post-signing PDF export.",
  },
  {
    id: "wc-evidence-packet-download",
    label: "Evidence packet download for Owner after packet built",
    status: "deferred",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-upload", "trim-ct-worker-packet"],
    notes: "Scoped read on evidence packet store with Owner-facing format.",
  },
  {
    id: "wc-bulk-ptc-edit",
    label: "Bulk-edit PTC capacity across counties",
    status: "deferred",
    flowIds: [],
    surfaceIds: ["trim-ct-op-jurisdiction"],
    notes: "UI multi-select on jurisdiction registry rows.",
  },
  {
    id: "wc-dlq-replay",
    label: "Dead-letter-queue replay from Exception queue",
    status: "deferred",
    flowIds: ["recover-exception"],
    surfaceIds: ["trim-ct-op-exceptions"],
    notes: "Job queue replay trigger with audit event.",
  },
  {
    id: "wc-copy-gate-reason",
    label: "Copy gate block reason visible to Operator",
    status: "wiring",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-op-exceptions"],
    notes: "Requires WF-02 to write suppression reason to case record.",
  },
  {
    id: "wc-outreach-scheduling",
    label: "Scheduled outreach batch by appeal window date",
    status: "deferred",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-op-county-data"],
    notes: "Job trigger with county-appeal-window date as input.",
  },
  {
    id: "wc-post-arb-lanes",
    label: "Post-ARB escalation eligibility and remedy election",
    status: "deferred",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-op-exceptions"],
    notes: "Requires WF-14 lanes and forum-eligibility computation.",
  },
  {
    id: "wc-escrow-flag",
    label: "Escrow / lender reserve classifier per parcel",
    status: "deferred",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-op-collections"],
    notes: "Servicer identification from loan data or Owner-flagged.",
  },
  {
    id: "wc-worker-timeline-alert",
    label: "Evidence cutoff date badge and deadline enforcement on Worker packet",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-worker-packet", "trim-ct-worker-hearing"],
    notes: "Requires WF-09 county packet validator.",
  },
  {
    id: "wc-worker-continued-outcome",
    label: "\"Continued\" hearing outcome type with reschedule state",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-worker-outcome"],
    notes: "State machine extension in WF-09.",
  },
  {
    id: "wc-worker-telemetry",
    label: "Worker no-show / cancellation structured reason codes",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-worker-outcome", "trim-ct-op-worker-dispatch"],
    notes: "Schema extension on Worker outcome report.",
  },
];

export const WIRING_FURNISH: WiringFacet[] = [
  {
    id: "wfu-days-in-state",
    label: "Days-in-state computed field on protest case",
    status: "implemented",
    flowIds: [],
    surfaceIds: ["trim-ct-owner-status"],
    notes: "Elapsed-time from state entry timestamp.",
  },
  {
    id: "wfu-contingency-lock-persist",
    label: "Contingency % locked at POA signing, immutable",
    status: "implemented",
    flowIds: ["consent-authorize"],
    surfaceIds: ["trim-ct-owner-authorize"],
    notes: "Stored in POA record; read-only after signing.",
  },
  {
    id: "wfu-county-freshness",
    label: "County data freshness field per county manifest",
    status: "partial",
    flowIds: [],
    surfaceIds: ["trim-ct-op-county-data"],
    notes: "Days-since-import tracked; alert threshold not yet configurable.",
  },
  {
    id: "wfu-valuation-methodology-tag",
    label: "Valuation methodology badge (equity / income / comps) per case",
    status: "wiring",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-owner-notice", "trim-ct-owner-status"],
    notes: "Outcome of WF-01 detection run; must be persisted on case.",
  },
  {
    id: "wfu-informal-offer-persist",
    label: "Informal offer amount persisted and Operator-visible",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-status", "trim-ct-op-exceptions"],
    notes: "Named field in WF-08.",
  },
  {
    id: "wfu-hearing-logistics-fields",
    label: "Hearing date / board / section / venue / appearance-mode as case fields",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-status", "trim-ct-worker-hearing"],
    notes: "Outcome of county scheduling in WF-09.",
  },
  {
    id: "wfu-worker-identity-visible",
    label: "Licensed Worker first name visible to Owner during hearing-active",
    status: "deferred",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-status", "trim-ct-worker-assignment"],
    notes: "Requires Owner-scoped read of Worker assignment.",
  },
  {
    id: "wfu-evidence-status-substatus",
    label: "Evidence prep substatus (comps / equity / income pending)",
    status: "wiring",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-owner-upload", "trim-ct-owner-status"],
    notes: "Sub-state on evidence_prep case state.",
  },
  {
    id: "wfu-invoice-trace",
    label: "Invoice trace lines (parcel, tax year, authorize date, savings calculation)",
    status: "wiring",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-invoice", "trim-ct-op-collections"],
    notes: "Invoice record must foreign-key to POA, savings calculation, and county bill.",
  },
  {
    id: "wfu-reduction-calculation",
    label: "Measured savings calculation (before/after x millage) as first-class fact",
    status: "wiring",
    flowIds: ["reduce-invoice"],
    surfaceIds: ["trim-ct-owner-reduction"],
    notes: "Computed in WF-10 and stored on case.",
  },
  {
    id: "wfu-annual-reenroll",
    label: "Recurrence enrollment flag on protest case after POA signing",
    status: "wiring",
    flowIds: [],
    surfaceIds: ["trim-ct-owner-status"],
    notes: "Set in WF-12; visible to Owner as chip.",
  },
  {
    id: "wfu-worker-pay-detail",
    label: "Per-appearance fee amount and expected payment date",
    status: "deferred",
    flowIds: ["evidence-hearing"],
    surfaceIds: ["trim-ct-worker-pay"],
    notes: "Worker pay record model with assignment -> outcome -> pay pipeline.",
  },
  {
    id: "wfu-audit-export",
    label: "Audit log export as CSV (date-range query)",
    status: "deferred",
    flowIds: [],
    surfaceIds: ["trim-ct-op-audit"],
    notes: "Query endpoint on immutable audit log.",
  },
  {
    id: "wfu-detection-lineage",
    label: "Detection run ID, roll-import date, model variant on each case",
    status: "wiring",
    flowIds: ["activate-notice"],
    surfaceIds: ["trim-ct-owner-notice", "trim-ct-op-county-data"],
    notes: "Requires WF-01 to write detection lineage to case record.",
  },
  {
    id: "wfu-poa-expiry",
    label: "POA expiration date field and alert trigger",
    status: "deferred",
    flowIds: ["consent-authorize"],
    surfaceIds: ["trim-ct-owner-authorize", "trim-ct-op-jurisdiction"],
    notes: "POA record must include scope and expiry.",
  },
];

export type CrossCuttingFinding = {
  id: string;
  rank: number;
  title: string;
  productSide: string;
  systemSide: string;
  sources: string;
  reconciliationNeeded: string;
  surfaceIds: string[];
  flowIds: string[];
};

/** Machine twin of `docs/sme/CROSS-CUTTING.md`, ranked as authored. */
export const CROSS_CUTTING_FINDINGS: CrossCuttingFinding[] = [
  {
    id: "cc-01",
    rank: 1,
    title: "ALG notice copy is a compliance-gated output, not just marketing copy",
    productSide: "First touch must use conditional, parcel-specific wording and avoid guaranteed savings, government-lookalike, or no-risk claims.",
    systemSide: "CTO needs a pre-notice substantiation packet and copy gate with roll facts, valuation support, confidence threshold, reviewer approval, approved claim text, and suppression rules.",
    sources: "pass1/solicitation-advertising-compliance.md; pass2/solicitation-advertising-compliance.md; pass1/valuation-mass-appraisal.md; pass2/valuation-mass-appraisal.md; pass1/trust-anti-scam-perception.md; pass2/trust-anti-scam-perception.md",
    reconciliationNeeded: "PM's Owner notice and consent states must use the same approved-claim vocabulary CTO enforces.",
    surfaceIds: ["trim-ct-owner-notice", "trim-ct-owner-trust", "trim-ct-op-exceptions"],
    flowIds: ["activate-notice"],
  },
  {
    id: "cc-02",
    rank: 2,
    title: "Licensure and jurisdiction standing gate the notice, not only filing or hearing",
    productSide: "A detected Owner may never see a served instance if Trim lacks jurisdiction standing or if the forum requires different authority.",
    systemSide: "The jurisdiction registry must run before outreach and include representative type, PTC/attorney/licensure status, solicitation regime, portal capability, owner-authority requirements, and forum variance.",
    sources: "pass1/representation-licensure.md; pass2/representation-licensure.md; pass1/solicitation-advertising-compliance.md; pass2/solicitation-advertising-compliance.md; pass1/judicial-arbitration-attorney.md; pass2/judicial-arbitration-attorney.md",
    reconciliationNeeded: "PM should model blocked/unavailable states from the same facts CTO uses to block notice, authorization, filing, hearing, arbitration, and litigation transitions.",
    surfaceIds: ["trim-ct-op-jurisdiction", "trim-ct-owner-notice"],
    flowIds: ["activate-notice", "consent-authorize"],
  },
  {
    id: "cc-03",
    rank: 3,
    title: "Texas sponsorship capacity is the launch throttle",
    productSide: "Owner demand cannot outpace named-human PTC capacity; Operators need capacity-visible county opening, acceptance, and reassignment states.",
    systemSide: "CTO needs named-human licensure, senior PTC sponsorship, max-10 supervision, exception evidence, CE/renewal monitors, reassignment, and case-level audit trails.",
    sources: "pass1/representation-licensure.md; pass2/representation-licensure.md; pass1/licensed-ptc-practitioner.md; pass2/licensed-ptc-practitioner.md",
    reconciliationNeeded: "PM launch and Operator outcomes must expose capacity as an operating state, and CTO scheduling must stop invalid outreach, filing, negotiation, and Worker dispatch.",
    surfaceIds: ["trim-ct-op-jurisdiction", "trim-ct-op-worker-dispatch"],
    flowIds: ["activate-notice", "evidence-hearing"],
  },
  {
    id: "cc-04",
    rank: 4,
    title: "The Worker hearing layer is real because board procedure creates bounded, human units of work",
    productSide: "Worker screens need assignment preview, authority proof, packet checklist, appearance mode, hearing script, outcome report, and pay/status boundaries.",
    systemSide: "CTO needs hearing states and dispatch constraints: notice, appearance mode, evidence cutoff, packet validator, Form 50-162 or alternate authority, check-in path, telemetry, no-show risk, and outcome schema.",
    sources: "pass1/appraisal-district-board.md; pass2/appraisal-district-board.md; pass1/licensed-ptc-practitioner.md; pass2/licensed-ptc-practitioner.md; pass1/representation-licensure.md; pass2/representation-licensure.md",
    reconciliationNeeded: "PM's Worker persona and admission table must match CTO's dispatch state machine.",
    surfaceIds: [
      "trim-ct-op-worker-dispatch",
      "trim-ct-worker-queue",
      "trim-ct-worker-packet",
      "trim-ct-worker-assignment",
      "trim-ct-worker-hearing",
      "trim-ct-worker-outcome",
    ],
    flowIds: ["evidence-hearing"],
  },
  {
    id: "cc-05",
    rank: 5,
    title: "Collections happen after the reduction because there is no escrow or automatic deduction",
    productSide: "The Owner gets benefit as a lower bill, refund, reserve credit, or escrow adjustment before Trim collects its fee.",
    systemSide: "CTO needs invoicing and collections after reduced: savings proof, corrected bill/order/refund proof, tax-rate math, card/ACH authorization status, due state, dunning, dispute reason, and collection audit.",
    sources: "pass1/licensed-ptc-practitioner.md; pass2/licensed-ptc-practitioner.md; pass1/mortgage-escrow.md; pass2/mortgage-escrow.md; pass1/tax-accounting-treatment.md; pass2/tax-accounting-treatment.md; pass1/collections-ar.md; pass2/collections-ar.md",
    reconciliationNeeded: "PM needs honest invoice and dispute states; CTO needs a collections pipeline without escrow assumptions.",
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-owner-invoice", "trim-ct-op-collections"],
    flowIds: ["reduce-invoice"],
  },
  {
    id: "cc-06",
    rank: 6,
    title: "The trust kit is a data requirement, not just a layout requirement",
    productSide: "First touch and served instance need private-company disclosure, named county/CAD, parcel/account ID, owner/situs match, official verification path, assessed value, record date, fee terms, self-file disclosure, and representative identity where relevant.",
    systemSide: "Detection must persist trust-kit fields and verification QA before outreach, including CAD URL/deep-link/manual-search capability, ID formatting, tax-year labels, snapshot dates, link reliability, and anti-phishing labeling.",
    sources: "pass1/trust-anti-scam-perception.md; pass2/trust-anti-scam-perception.md; pass1/county-data.md; pass2/county-data.md; pass1/solicitation-advertising-compliance.md; pass2/solicitation-advertising-compliance.md",
    reconciliationNeeded: "PM owns what the Owner sees; CTO owns whether those facts can be verified against official county data.",
    surfaceIds: ["trim-ct-owner-notice", "trim-ct-owner-trust"],
    flowIds: ["activate-notice"],
  },
  {
    id: "cc-07",
    rank: 7,
    title: "The county-data moat is operational depth, not secret data",
    productSide: "Launch should be county-depth over county-breadth because Owner promises, deadlines, verification links, filing paths, Worker instructions, and recurrence vary by CAD.",
    systemSide: "CTO needs county manifests, CAMA/vendor adapters, canonical schema plus exception flags, GIS metadata, appeal calendars, e-file capability, portal credential/PIN handling, PIA fallback budgets, freshness guards, and parser QA.",
    sources: "pass1/county-data.md; pass2/county-data.md; pass1/valuation-mass-appraisal.md; pass2/valuation-mass-appraisal.md; pass1/appraisal-district-board.md; pass2/appraisal-district-board.md",
    reconciliationNeeded: "PM should not phrase launch as Texas-on when county readiness is a multi-field operating state.",
    surfaceIds: ["trim-ct-op-county-data", "trim-ct-op-jurisdiction"],
    flowIds: ["activate-notice", "evidence-hearing"],
  },
  {
    id: "cc-08",
    rank: 8,
    title: "Income documents are optional for detection but decisive for maximizing commercial appeals",
    productSide: "Owner upload UX must frame rent roll, P&L, leases, occupancy, concessions, condition evidence, and redaction guidance as case-improving, not required to detect the opportunity.",
    systemSide: "CTO needs evidence-upgrade states that separate public-data signal, income-approach readiness, confidential owner evidence, ARB-retainable packet, and litigation hold.",
    sources: "pass1/valuation-mass-appraisal.md; pass2/valuation-mass-appraisal.md; pass1/licensed-ptc-practitioner.md; pass2/licensed-ptc-practitioner.md; pass1/appraisal-district-board.md; pass2/appraisal-district-board.md; pass1/judicial-arbitration-attorney.md; pass2/judicial-arbitration-attorney.md",
    reconciliationNeeded: "PM's upload framing and CTO's evidence model must preserve the public-data ALG wedge while making private evidence strong enough for ARB use.",
    surfaceIds: ["trim-ct-owner-upload", "trim-ct-owner-status", "trim-ct-worker-packet"],
    flowIds: ["evidence-hearing"],
  },
  {
    id: "cc-09",
    rank: 9,
    title: "Escrow and lender reserves change felt win timing even when Trim's first wedge is direct-pay commercial",
    productSide: "Owner status and invoice copy must separate documented savings from visible cash timing for escrowed mortgages and lender reserves.",
    systemSide: "CTO needs escrow/lender classifiers, corrected bill/refund proof, servicer notice packet, loan-document control map, reserve-release triggers, and timing overlays.",
    sources: "pass1/mortgage-escrow.md; pass2/mortgage-escrow.md; pass1/tax-accounting-treatment.md; pass2/tax-accounting-treatment.md",
    reconciliationNeeded: "PM preserves the direct-payer wedge while CTO keeps reduced, invoiced, collected, and cash_received separate.",
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-owner-invoice", "trim-ct-op-collections"],
    flowIds: ["reduce-invoice"],
  },
  {
    id: "cc-10",
    rank: 10,
    title: "Post-ARB escalation is a separate legal product lane, not a generic \"appeal more\" button",
    productSide: "After denial or partial reduction, Owners need forum-specific choices with separate authority, deadline, deposit, counsel, tax-payment preservation, and economics.",
    systemSide: "CTO needs remedy gates for order type, receipt date, deadline, tax payment, value ceiling, forum eligibility, remedy-election lock, arbitration deposits, separate appointment, attorney consent, litigation hold, and discovery workspace.",
    sources: "pass1/judicial-arbitration-attorney.md; pass2/judicial-arbitration-attorney.md; pass1/representation-licensure.md; pass2/representation-licensure.md; pass1/licensed-ptc-practitioner.md; pass2/licensed-ptc-practitioner.md",
    reconciliationNeeded: "PM and CTO must keep ordinary protest states distinct from post-ARB legal remedies.",
    surfaceIds: ["trim-ct-owner-reduction", "trim-ct-op-exceptions"],
    flowIds: ["reduce-invoice", "recover-exception"],
  },
];
