/**
 * Trim CT jurisdiction data — Texas counties with PTC capacity, fee caps,
 * appeal windows, CAMA freshness, and e-file availability.
 */
import type { TrimJurisdiction } from "./trimTypes";

export const TRIM_JURISDICTIONS: TrimJurisdiction[] = [
  {
    countyCode: "TX-HAR",
    countyName: "Harris County",
    cad: "HCAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 7,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice, whichever is later",
    appealDeadline: "2025-05-15",
    eFileAvailable: true,
    camaFreshness: "current",
    rollImportStatus: "ok",
    compCoverage: "high",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    licensedAgent: "Maria Gutierrez (TDLR #12309)",
    rolloutGate: "open",
  },
  {
    countyCode: "TX-BEX",
    countyName: "Bexar County",
    cad: "BCAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 4,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice, whichever is later",
    appealDeadline: "2025-05-15",
    eFileAvailable: true,
    camaFreshness: "current",
    rollImportStatus: "ok",
    compCoverage: "high",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    licensedAgent: "David Okafor (TDLR #14872)",
    rolloutGate: "open",
  },
  {
    countyCode: "TX-TRV",
    countyName: "Travis County",
    cad: "TCAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 6,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice",
    appealDeadline: "2025-05-15",
    eFileAvailable: true,
    camaFreshness: "current",
    rollImportStatus: "ok",
    compCoverage: "high",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    licensedAgent: "Sarah Chen (TDLR #10044)",
    rolloutGate: "open",
  },
  {
    countyCode: "TX-COL",
    countyName: "Collin County",
    cad: "CCAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 2,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice",
    appealDeadline: "2025-05-15",
    eFileAvailable: true,
    camaFreshness: "current",
    rollImportStatus: "ok",
    compCoverage: "medium",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    rolloutGate: "open",
  },
  {
    countyCode: "TX-DAL",
    countyName: "Dallas County",
    cad: "DCAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 8,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice",
    appealDeadline: "2025-05-15",
    eFileAvailable: true,
    camaFreshness: "current",
    rollImportStatus: "ok",
    compCoverage: "high",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    licensedAgent: "James Rivera (TDLR #11234)",
    rolloutGate: "open",
    note: "Near PTC senior-sponsor cap — flag new enrollments.",
  },
  {
    countyCode: "TX-TAR",
    countyName: "Tarrant County",
    cad: "TAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 5,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice",
    appealDeadline: "2025-05-15",
    eFileAvailable: true,
    camaFreshness: "current",
    rollImportStatus: "ok",
    compCoverage: "high",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    licensedAgent: "Aisha Patel (TDLR #13801)",
    rolloutGate: "open",
  },
  {
    countyCode: "TX-MON",
    countyName: "Montgomery County",
    cad: "MCAD",
    state: "TX",
    status: "active",
    ptcCapacity: 10,
    ptcUsed: 1,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice",
    appealDeadline: "2025-05-15",
    eFileAvailable: false,
    camaFreshness: "stale",
    rollImportStatus: "pending",
    compCoverage: "low",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    rolloutGate: "limited",
    note: "CAMA data stale — comp coverage insufficient for reliable evidence builds. Roll import pending.",
  },
  {
    countyCode: "TX-ELP",
    countyName: "El Paso County",
    cad: "EPCAD",
    state: "TX",
    status: "blocked",
    ptcCapacity: 10,
    ptcUsed: 0,
    feeCapPct: 20,
    appealWindowNote: "May 15 or 30 days from notice",
    appealDeadline: "2025-05-15",
    eFileAvailable: false,
    camaFreshness: "unknown",
    rollImportStatus: "failed",
    compCoverage: "low",
    entitySignerRule: "Officer with deed authority or TDLR-licensed agent of record",
    rolloutGate: "blocked",
    note: "Blocked — TDLR licensed agent of record not assigned; roll import failed.",
  },
];
