/**
 * Mark SmeItems whose Implementation is written but NOT fully planted in CT.
 * Only sets implementationPlant: "not_done" — no "implemented" tags, no SME UI.
 *
 * Run: npx tsx scripts/tag-sme-plant-gaps.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { allSmeItems } from "../src/app/register/trace/smeRegistry";
import { PRODUCT_UI_REFS } from "../src/app/register/trace/productUiRefs";
import { IMPLEMENTATION_UI_REFS } from "../src/app/register/trace/implementationUiRefs";
import { SURFACES } from "../src/app/register/trace/surfaces";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const refs = [...PRODUCT_UI_REFS, ...IMPLEMENTATION_UI_REFS];
const labels = [...new Set(refs.map((r) => r.label))].sort((a, b) => b.length - a.length);
const catalog = new Set(SURFACES.map((s) => s.id));

const CORE_NEW = ["Claim form packet", "Filing method", "Expected days", "Fee cap %"];

function lineHasPlantedNewAffordance(line: string): boolean {
  if (CORE_NEW.some((l) => line.includes(l))) return true;
  const idx = line.toLowerCase().indexOf("you can now");
  const after = idx === -1 ? line : line.slice(idx);
  return IMPLEMENTATION_UI_REFS.some((r) => {
    if (!r.surfaceId || !catalog.has(r.surfaceId)) return false;
    return after.includes(r.label) || line.includes(r.label);
  });
}

function lineHasClickableParent(line: string): boolean {
  const hit = labels.find((l) => line.includes(l));
  if (!hit) return false;
  const ref = refs.find((r) => r.label === hit);
  return Boolean(ref?.surfaceId && catalog.has(ref.surfaceId));
}

function isNotDone(implementation: string | undefined): boolean {
  if (!implementation?.trim()) return true;
  const lines = implementation.split("\n").filter(Boolean);
  for (const line of lines) {
    if (!lineHasClickableParent(line)) continue;
    if (!lineHasPlantedNewAffordance(line)) return true;
  }
  if (!lines.some(lineHasPlantedNewAffordance)) return true;
  return false;
}

const notDoneIds = new Set<string>();
for (const item of allSmeItems()) {
  if (isNotDone(item.implementation)) notDoneIds.add(item.id);
}

const files = [
  "src/app/register/trace/recoveryClaimsConsiderations.ts",
  "src/app/register/trace/considerations/holderComplianceConsiderations.ts",
  "src/app/register/trace/considerations/escheatmentLegalConsiderations.ts",
  "src/app/register/trace/considerations/contingencyFeeConsiderations.ts",
  "src/app/register/trace/considerations/stateAdminConsiderations.ts",
  "src/app/register/trace/considerations/entityResolutionConsiderations.ts",
  "src/app/register/trace/considerations/trustAntiScamConsiderations.ts",
  "src/app/register/trace/considerations/taxAccountingConsiderations.ts",
  "src/app/register/trace/considerations/finderLicensureConsiderations.ts",
  "src/app/register/trace/considerations/paymentsRemittanceConsiderations.ts",
];

let tagged = 0;

for (const rel of files) {
  const full = path.join(root, rel);
  let text = fs.readFileSync(full, "utf8");
  text = text.replace(/\n\s*implementationPlant:\s*"(?:not_done|implemented)",?/g, "");

  for (const id of notDoneIds) {
    const re = new RegExp(`(id:\\s*"${id}"[\\s\\S]*?)(\\n\\s*status:\\s*")`, "m");
    if (!re.test(text)) continue;
    text = text.replace(re, (match, head: string, statusStart: string) => {
      if (head.includes(`id: "${id}"`) && head.includes("implementationPlant:")) return match;
      // ensure we only rewrite the first status after this id (non-greedy already)
      tagged++;
      return `${head}\n    implementationPlant: "not_done",${statusStart}`;
    });
  }

  fs.writeFileSync(full, text, "utf8");
}

const sorted = [...notDoneIds].sort();
const indexPath = path.join(root, "src/app/register/trace/implementationPlantGaps.ts");
fs.writeFileSync(
  indexPath,
  `/**
 * Implementation plant gaps — written in SME, not yet assembled in CT.
 * Ticket-board source. Not rendered in the SME pane.
 *
 * Regenerated by: npx tsx scripts/tag-sme-plant-gaps.ts
 */
export const IMPLEMENTATION_NOT_DONE_IDS = ${JSON.stringify(sorted, null, 2)} as const;

export type ImplementationNotDoneId = (typeof IMPLEMENTATION_NOT_DONE_IDS)[number];

export function isImplementationNotDone(id: string): boolean {
  return (IMPLEMENTATION_NOT_DONE_IDS as readonly string[]).includes(id);
}
`,
  "utf8",
);

const done = allSmeItems().length - notDoneIds.size;
console.log(`total ${allSmeItems().length}`);
console.log(`not_done ${notDoneIds.size}`);
console.log(`done (no tag) ${done}`);
console.log(`file injections ${tagged}`);
console.log(`index ${path.relative(root, indexPath)}`);
